### ISSUE TITLE
Supports friendly connection name when connecting to RabbitMQ server?

### ISSUE THREAD

**Issue by C-Duv** [logstash-plugins/logstash-output-rabbitmq#74]
Since rabbitmq/rabbitmq-server#104, RabbitMQ clients can pass a "friendly connection name" to the server when connecting.
This is not a reliable identifier but is shown in the server's management web interface and can serve for debugging.

I tried the following that uses the `arguments` parameter without success (data is sent to RabbitMQ, I can see the client in the RabbitMQ administration page but it has no friendly name):

```
input {
    generator {}
}
filter {
    sleep { time => 0.01 }
}
output {
    rabbitmq {
        host => "127.0.0.1"
        port => 5672
        vhost => "/"
        user => "guest"
        password => "guest"
        exchange => "test"
        exchange_type => "topic"
        key => "test"
        codec => "json"
        arguments => {
            connection_name => "foo-bar-logstash"
        }
    }
}
```

Is such feature implemented in the rabbitmq input & output plugins?

I uses Logstash v5.6.8
and RabbitMQ v3.7.3 (with other clients, in Python/NodeJS/etc., on which `connection_name` works)

**Comment by jakelandis** [comment]
It looks like maybe https://github.com/logstash-plugins/logstash-output-rabbitmq/issues/44 is the root problem here, and I believe the fix for that (and this) If I am reading the corresponding issues correctly...  the fix is likely needed in https://github.com/logstash-plugins/logstash-mixin-rabbitmq_connection project. 

@C-Duv - if you agree that this needs to be set on the connection object, and should be present for both input and output could you close this issue and re-open it over  at https://github.com/logstash-plugins/logstash-mixin-rabbitmq_connection

**Comment by C-Duv** [comment]
Being a connection parameter and for both input and output plugin, you are right: it shoud indeed be on _logstash-plugins/logstash-mixin-rabbitmq_connection_. I'll re-open there.
